### ISSUE TITLE
Add number of days to retain ARM-TTK results

### ISSUE THREAD

**Issue by shaharz-lb** [microsoft/action-armttk#11]
The results of the ARM-TTK are uploaded to the GitHub artifactory.
I want to add a new parameter to control the number of days this report will saved in the artifactory.
In our company there is limited artifactory and we need to clean old files from it.
The suggestion is to add a new parameter:
```
  armttkResultsRetention:
    description: "Number of days to retain ARM-TTK results"
    required: false
    default: 30
```
And use it in the `Publish Test Results` step:
```
    - name: Publish Test Results
      uses: actions/upload-artifact@v3
      with:
        name: ARMTTKResults
        path: ./armttk.xml
        retention-days: ${{ inputs.armttkResultsRetention }}
```

I can open a new PR if you give me permission to do so.
